### ISSUE TITLE
Update libjpeg turbo to 2.1.x or newer

### ISSUE THREAD

**Issue by bk138** [bk138/droidVNC-NG#141]
Preliminary tests showed that 2.1.x seems to have
* more compression, less usage of available throughput (which is good for low-throughput links) :+1: 
* more tearing :-1: (#1 might help?)
* less effective throughput measured w/ MultiVNC

# todos
- [ ] double check MultiVNC's stats
- [ ] check compression settings in libvncserver
- [x] integrate via cmake externalproject as that's the only way newer libjpeg-turbo supports
