### ISSUE TITLE
Inputs not working on some Google TVs

### ISSUE THREAD

**Issue by wirtualka85** [bk138/droidVNC-NG#244]
Hello

I have installed droidVNC-. NG 2.7.3 on TCL 75C805 Google TV.
On the TV I have granted all permissions to the droidVNC-NG application.

I connect from a computer with UltraVNC.
Remote mouse and keyboard do not work.

Only the ESC, END and HOME buttons on the keyboard work.

Please repair.

# TODOs
- [x] implement basic DPAD focus nav
- [x] grab focus on app start / window change / focus nav fail -> nav fail for now
- [x] use GLOBAL_ACTION_DPAD_* on API >= 33
- [x] implement focus nav via Tab
- [x] retest with multiline edit widgets
- [x] fix client list

**Comment by bk138** [comment]
Thanks for your report! I tested this on a Google TV emulator, it works there. 

Can you please try to:
- check that accessibility service for droidVNC-NG is enabled in Settings
  - switch it off and on again and retry 
- if that does not work, get a complete logcat output of the error case
- try another remote desktop app to see if it has the same issues? IIRC anydesk has a TV version as well...

**Comment by wirtualka85** [comment]
-------------------------------------
AnyDesk
The keyboard only works after installing AnyDesk plugin ad1.
The mouse doesn't work.
-------------------------------------
droidVNC-NG

I tested with other VNC clients, same behavior.
I checked availability a few times.
Without accessibility the ESC, END and HOME keys do not work.

###################
My workaround.
On the computer I see the TV desktop.
I control the TV from my phone using the Google TV app.

**Comment by bk138** [comment]
@wirtualka85 can we close this issue then?

**Comment by wirtualka85** [comment]
No.
The droidVNC-. NG 2.7.3 application does not work properly with TV.
I will perform tests on another TV Google TV TCL 65c645 and let you know if the application works or not.

**Comment by bk138** [comment]
You can try that. I fear that there are bugs in the underlying a11y implementation if other apps are also not working.

**Comment by bk138** [comment]
You can also give alphavnc a try, please post the results here if you so so.

**Comment by bk138** [comment]
Tentatively closing, feel free to post info here once available, we can then re-open.

**Comment by cannondale0815** [comment]
Also having this issue of not being able to send mouse clicks across to the Android TV that's running droidVNC 2.8.0. It's a Phillips TPM191E with Android TV 11.

I am using TightVNC viewer on a Windows 11 PC. Keyboard shortcuts like ESC work fine. But mouse clicking doesn't work, so I have no way of navigating the TV remotely.

Thank you for this excellent piece of software btw, I am using it successfully on my parent's mobile phones to provide remote support to them :)

**Comment by bk138** [comment]
@cannondale0815 thanks for reporting. If at all possible, I need logcat output, best annotated with what you were trying at a specific timestamp.

**Comment by pozineg** [comment]
Hi,

I can confirm the same issue user wirtualka85 reported earlier. What happens on my both Google TVs was described in Exact words. I'm opening this unresolved issue again as it has been previously closed for some reason.

I've tried all your suggestions plus restart/reinstall but nothing works. Would you mind trying to resolve it?

Logcat dumped while running both: app with all privileges allowed  and vnc connection active - [logcat.txt](https://github.com/user-attachments/files/18230027/logcat.txt)

Thanks

**Comment by bk138** [comment]
> Logcat dumped while running both: app with all privileges allowed and vnc connection active - [logcat.txt](https://github.com/user-attachments/files/18230027/logcat.txt)

Logs look unsuspicious. What I find strange is that there are no [OnKeyEvent logs](https://github.com/bk138/droidVNC-NG/blob/master/app/src/main/java/net/christianbeier/droidvnc_ng/InputService.java#L312) - did you try to enter text with the keyboard somewhere? Then again, https://github.com/bk138/droidVNC-NG/blob/master/app/src/main/java/net/christianbeier/droidvnc_ng/InputService.java#L486 is triggered somewhere, so `isInputEnabled` is probably true...

**Comment by pozineg** [comment]
Keyboard input works in edit mode - when keyboard present on the TV screen.

Sent with Spark

**Comment by bk138** [comment]
Guys, we need logcat dumps together with what you tried. Otherwise this issue is unactionable 🙁.

**Comment by pozineg** [comment]
Hi,
Steps taken:
1. Connected to TV via ADB on port 5555,
2. Started droidVNC-NG service on Google TV with mouse cursors on and all 4 permissions granted,
3. Connected to Google TV via VNC on the android phone,
4. Moving mouse with effect bout no clicks, tap, double tap, tap and hold, 2 finger tap or any other command inn effect apart form the movement on Google TV and VNC screens.
5. Using TV remote moved to edit Start Delay setting in droidVNC_NG.
6. Key entries, Enter and Delete worked.
7. Moved to a Google TV's App search edit screen with a remote virtual keyboard popped up.
8. Entered app name to search via VNC, but enter didn't work, only remote command sent activated search.
9. Logcat dump taken -attached below.
Hope this helps,
Thanks for investigating.
[Uploading logcat.txt…]()

**Comment by bk138** [comment]
@pozineg thanks for the effort, the download link is broken, however.

**Comment by pozineg** [comment]
Hi Christian,

Sorry for a delay.
Both logs attached low - first from an issue reopening and second one from today's debug session. Hope upload works this time :-)

Thank you,

[DroidVNC-NG - logcat - 2024.12.23.txt](https://github.com/user-attachments/files/18271085/DroidVNC-NG.-.logcat.-.2024.12.23.txt)
[DroidVNC-NG - logcat - 2024.12.29.txt](https://github.com/user-attachments/files/18271087/DroidVNC-NG.-.logcat.-.2024.12.29.txt)

**Comment by IagonaDevTeam** [comment]
Hey everyone, does someone have any news on this issue?

**Comment by bk138** [comment]
Unfortunately not. Am a bit clueless here tbh. It would help if someone with access to the hardware could make a table or list which other solutions work and if so, how they do it. Open source would be nice so we can get code insights.

**Comment by bk138** [comment]
> I'm having the same issue on my Own Android TV. I can click Esc and it works as the Home command, but the mouse clicks don't work. I'll find out how to collect logs and provide them.

@andresberge what would also help is to try other tools like alphavnc, teamviewer, anydesk etc and see if they work and collect logs for them. All a lot of work....

**Comment by andresberge** [comment]
> teamviewer and alphavnc say they're not compatible with my Onn Android TV. AnyDesk has the same behavior, I can connect remotely, but can't control the device. I also confirmed that I can use the remote keyboard to write on text fields on the TV, which gave me this thought: Is there a way to use the keyboard to reproduce the directional pad and select button? (something like W, A-S-D, X)

I was able to install the teamviewer server, but not the plugin for remote control, which is not supported on my Onn Android TV.

**Comment by bk138** [comment]
> Is there a way to use the keyboard to reproduce the directional pad and select button? (something like W, A-S-D, X)

Well thats already there, cursor keys and enter...

**Comment by andresberge** [comment]
> > Is there a way to use the keyboard to reproduce the directional pad and select button? (something like W, A-S-D, X)
> 
> Well thats already there, cursor keys and enter...

I see... that doesn't work for me, either :-(

**Comment by andresberge** [comment]
@bk138 is there a way to send the adb shell commands through MultiVNC?
Sending these ones through adb worked on my Onn Android TV:
19 -->  "KEYCODE_DPAD_UP" 
20 -->  "KEYCODE_DPAD_DOWN" 
21 -->  "KEYCODE_DPAD_LEFT" 
22 -->  "KEYCODE_DPAD_RIGHT" 
23 -->  "KEYCODE_DPAD_CENTER" 
(if that's what the cursor arrows are supposed to do, apologize for asking the same thing)
Thanks!

**Comment by bk138** [comment]
@andresberge are you on android 13 or newer? Because https://github.com/bk138/droidVNC-NG/blob/30b0f656531b7ca120efd66faaf022d832281996/app/src/main/java/net/christianbeier/droidvnc_ng/InputService.java#L399

**Comment by andresberge** [comment]
I'm on android 12.
I'll take a look at how to build your project and install the apk so I can try things in that file, I'm a complete newbie here.

**Comment by arktronic** [comment]
I'm seeing the same issue on a Hisense Google TV (also Android 12). However, I can confirm that mouse and keyboard arrow keys work correctly when using [scrcpy](https://github.com/Genymobile/scrcpy). I've even tried switching the keyboard input mode to [UHID](https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#uhid) and that works as well, in addition to the default SDK mode.

**Comment by nonobio** [comment]
Hi, I just discovered this application, thank you very much, it allows me to see the display of my box remotely via my Windows and TightVNC PC. On the other hand, as mentioned above, I cannot control my box with my keyboard and my mouse, only the special keys work (Ctrl-Shift-Esc, End, Escape). I still noticed that the other keys work if I am on a text field.

**Comment by bk138** [comment]
@nonobio please also post your android version and logs. Logs are what helps most.

**Comment by nonobio** [comment]
@bk138 My Android TV version is 12.
Here is the other information in About page:
![Image](https://github.com/user-attachments/assets/2a624029-291b-4d74-b8b8-33041cbb63ca)

Regarding the logs, where are they?

**Comment by bk138** [comment]
I have a user who reports that input is working on a TV with Android 14 so you guys might want to upgrade if at all possible.

**Comment by nonobio** [comment]
My Mecool KM2 Plus has no updates available at the moment (I am on Android 12)

**Comment by MrMisterSir** [comment]
Yeah so uhh I had the same problem. I made a crutch to bypass it using just android "input tap/input swipe". I'm not sure if it requires root though, but if you're interested, here's what I modified in InputService.java:

1) taps
In the onPointerEvent:
// up, was down
			if ((buttonMask & (1 << 0)) == 0 && inputContext.isButtonOneDown) {
				inputContext.isButtonOneDown = false;
				instance.endStroke(inputContext, x, y);
				if (Build.VERSION.SDK_INT == Build.VERSION_CODES.R) {
					Shell.su("input tap " + x + " " + y).exec();
				}
			}
2) swipes
In the createSwipe before return:
if (Build.VERSION.SDK_INT == Build.VERSION_CODES.R) {
			Shell.su("input swipe " + x1 + " " + y1 + " " + x2 + " " + y2 + " " + duration).exec();
		}
3) contextmenu (long press)
In the longPress:
if (Build.VERSION.SDK_INT == Build.VERSION_CODES.R) {
			Shell.su("input swipe " + x + " " + y + " " + x + " " + y + " 500").exec();
		}

The if (Build.VERSION.SDK_INT == Build.VERSION_CODES.R) is because its clunky af and I dont think it should clutter other bugless android versions.
Thread says "help wanted" so... thought you might need it? Respond anyway, hope it helps. Works clunky but best I got for you.
P.S. Didn't make a pull request bc VERY clunky and needs review first.

**Comment by bk138** [comment]
Hey @MrMisterSir thanks for the snippet! To integrate this, we would need at least
- a check that we're running on affected Android version (easy)
- a check that we're running on any TV (maybe possible?)
- action should not require root

**Comment by LetArch** [comment]
I read the issue and tryed to run **droidVNC-NG** on a tablet **Samsung SM-X115 with Android 14** - it's worked fine, input worked! And therefore I thought - just will buy tvbox with android 14! Buyed **RT-X2 (ATV 14)** and run on it droidvnc-ng 2.15 - and... _input not work... So bad..._

**Comment by githubfan1960** [comment]
Hello everyone,

An update on the situation using the Thomson 270. Well, we finally got the update to android 14 but I'm sorry to have to inform that the situation is still the same. No control with arrow keys or mouse possible. I had such high hopes of it working after some users say their machines with v14 do respond.

The only solution at the moment is still to use scrcpy. I am hoping, hoping (with sugar on top) that bk138 will so kindly find a solution for us tv box users. Scrcpy, even though a good alternative since there is nothing else availbale atm, works over adb, and often gives problems with adb permissions: For example after tailscale updates. With Droidvnc we could let the server run on startup and the problem is solved.

**Comment by bk138** [comment]
Hi all,
Building on the great foundations laid out by @dustinmcafee I could come up with something that should allow decent keyboard navigation (not only on TVs) starting with Android 13 and onwards and working OK with some rough edges on earlier Android versions.

Please try out the attached apk and report back here.

I tested on various TV emulator images where the mouse is working but I was pretending it doesn't.

* Expectations:
   * on Android 13 and newer everything should just work. Navigate with cursor keys, click with Enter.
   * on earlier Android versions:
      * sometimes the focus gets lost; what helped me is to hit Pos1/Home in the VNC viewer and it reset
      * some elements like settings are simply not clickable via Enter

[app-debug.zip](https://github.com/user-attachments/files/24107912/app-debug.zip)

**Comment by githubfan1960** [comment]
Ok, looking forward to the update. Thank you for replying :)

**Comment by githubfan1960** [comment]
Just installed the latest update 2.18.0 from the playstore. 
It's working much better! :)
Everything works pretty much as expected except the ENTER key functioning as the OK button does not work in 
all apps.  Kodi for example: You can move around fine with the arrow keys in Kodi but the OK button (ENTER KEY) does
not work. Mouse clicks are also not responsive so no way to select or activate using the mouse cursor. 
Accessibility is working fine now.

**Comment by cannondale0815** [comment]
> https://buymeacoffee.com/christianbeier :-P

Appreciation sent -- happy holidays! :)
